server:
  port: 9898
  max-http-header-size: 1024000
spring:
  application:
    name: youxinservice
  mvc:
    favicon:
      enabled: false
  data:
    mongodb:
      uri: mongodb://120.76.101.139:28018/admin
      host: 120.76.101.139
      username: 
      password: 
      database: youxinappa
      port: 28018 
      connect-timeout: 20000
      socket-timeout: 20000
      max-wait-time: 2000
      max-connection-idle-time: 60000

  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0
    isCluster: false
    timeout:
      seconds: 10000
    jedis:
      pool:
        max-active: 10000
        max-wait:
          seconds: 10000
        max-idle: 1000
        min-idle: 1000
        
       
authorizationfilter:
  requestUriList[0]: /user/register
  requestUriList[1]: /user/login
  requestUriList[2]: /other/randcode/sendSms
  requestUriList[3]: /user/updatePwdForSms
  requestUriList[4]: /config/get
  requestUriList[5]: /user/logoutbak
  requestUriList[6]: /user/sdkLogin
  requestUriList[7]: /user/getOpenids
  requestUriList[8]: /wxpay/callBack
  requestUriList[9]: /alipay/callBack
  requestUriList[10]: /other/getImgCode
  requestUriList[11]: /pp/isPermission
  requestUriList[12]: /alipay/change
  

youxin:
  apiKey: youxin 
  #是否检验接口 0不检验，1检验
  isAuth: 0 
  #是否保存请求日志 0否，1是
  isSaveRequestLogs: 0 
  #redis地址
  redisAddr: redis://127.0.0.1:6379
  #友讯号
  accountTitle: yx
  #是否开启定时任务
  openTask: 0
  #yunxinappkey
  yunxinappkey: faeb0ec0ce3871b699119420790c8789
  #yunxinappaecret
  yunxinappaecret: d53d9d0cd80b
## 阿里云短信服务
smsconfig:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accesskeyid: LTAIPf3JXTTdhbVU
  accesskeysecret: acMpNNTELzuMKgJisolq9DztjTLmFE
  signname: 友信IM
  chinase-templetecode: SMS_164220086
  ## 图形验证码是否启用0不启用 1起用
  isstart: 0
  
###微信支付相关配置
wxconfig:
  appid: wx52ac911627154d31
  mchid: 1559973071
  secret: 31bbedb38c0707d6da871e353ff1f313
  api-key: youxunyouxunyouxunyouxunyouxunyx
  call-back-url: http://youxinapp.cn/wxpay/callBack
  pk-path: D:/Eclipse/WorkPace/mianshi-parent/mianshi-im-api/youxin.p12
  
#支付宝支付相关配置
alipayconfig:
  appid: 2019103168821258
  pid: 2088631593752425
  app-private-key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCeKIDfNGplMAwyEdzgHhZAvitrde1qTLqAwTKlfgFliPlArvtzWwKwxGr7z/fw/2n/FDcXXqcwpHBz8aNNzLD0SRHZkXW2xXVhoWNQNDs6e20JtxR3dONRsccEWuqmfj177grxoRp9WJHcMLOEoR3KznhZ6e5zUnekLLPtGZy9D0hmtLGswid02n49Zmtkd7FKy9cJljGoLol+F70j16j6SyYiTur5PbwVsMxnlcHuxi7OETZDkabOTnD8ZggMPSa+KvJjX6T/Q0WVLbS8pXqqiVq5MMrsF0xGm6JNDikC4qHCwwJju4rKx9/r0PdwmGhzEYm9FvHvT0plKdKBnk4DAgMBAAECggEAZLIpCvOWYgJrYV2aIV9Gj8YEYxDcLffYLq3TDybgwMKq35IJKnLhjaYg716D3/7ef7dhNBHhpMitiERq0tfmOkJjiQBh0BJ8H8LfNmtq4ls/GxZjg4L6UEM+EPnJuGNbxhHTCfCmqvO/OlAPm/vwufUnDygv12DEJ9UGYYkTEBMqHj/bMExvZ5fJ9zILZ5yRJJiAb1zIw+seOT6tKRT88VLBFoErA56Qg/MRTRsTidzXYpk87KkYgh4uBb8FX0OYIW4esKcRY8uO82r3zwBpYGzMd+MIlIGZrPvVxb4t7bjHHWQZYzxFZyfWlkDn34f6bFsbF6ickLAA+NUWXkZEwQKBgQD8MmdwCfwP4QSxaxZ9SLSHSKBwAYA0kA1aTzkp79X5j9pJzIbTO9sA7gtCJDKoOsBSNd7mxr1jSRluVEgnZus7OVJr/+iNKwyh7eMB6JJRZZ9IDl5/THVO+WdV6KyOzniKATMSM7EDWW9N089QlTOzzA4gcNvS34JeUOVOy3HkUQKBgQCgixEcFkp0wnr58k0qYiVyRlWhnKZjLkQw9cgLOP/xUaG4KobEdHPGJWdYa1Zu6pAkk61ZmWHunPVmK89Tt49yuLlbaZPRcJ65vyiREofNcZcbPXtbGXpd52LvHTmKhgvAeY0l5lvUZQ45oo5bbWnfMTgatm8loXkBkm7NuzmcEwKBgBhIKhlpfLFysub6LpIle+xCm9/s5REqhX6afiCBjRKYPSY54QlZi/6M7NyTa6Uy8u13bly96eIzWZV72+6fRCrRnBP18cgVywOUSfUXFW9s32cqqwKKtAjEjqSA4IxnaMew0eAAxhxSchsGN8HEe9Pl475P33pwNrcqBsoNYIvhAoGAGuby2QgLNgGY5eVqdN25dKrAkrJTV29bUfD9spO8n82UEe5eYvE4rU17Qd/Kvg9kVBzDAa6oMHnwzUwuE9NAoHK/7MeGU6RRlMKpo5W9V/ne3luxHhTo4m9xrqvxBntr4Lb9pgox/Sdp+NJ6lGuDQDlZM3C6s02Zn1/QXX0wLC0CgYBJfMfVzNNSqBmhJeIWgH6RzmNk6vquQ8cKb7rnu1BuovCol4pGfIxLykm8GJLG+8w5q1BUS51l9d3CsDAP89t0ltrYx0RGVFm+f0Tc54LzlyWqvCmR7a1g2/yLtbxj++2TwAngg1GlscXNAtLw86J2jW9JjMphLfV+7G4lvcX+ng==
  charset: utf-8
  alipay-public-key: MIIDsjCCApqgAwIBAgIQICABFSKB4AIiakFV63aZkjANBgkqhkiG9w0BAQsFADCBgjELMAkGA1UEBhMCQ04xFjAUBgNVBAoMDUFudCBGaW5hbmNpYWwxIDAeBgNVBAsMF0NlcnRpZmljYXRpb24gQXV0aG9yaXR5MTkwNwYDVQQDDDBBbnQgRmluYW5jaWFsIENlcnRpZmljYXRpb24gQXV0aG9yaXR5IENsYXNzIDIgUjEwHhcNMjAwMTE1MDMxMzM2WhcNMjIwMTE0MDMxMzM2WjCBkjELMAkGA1UEBhMCQ04xLTArBgNVBAoMJOmHjeW6huWPi+S/oei9r+S7tuenkeaKgOaciemZkOWFrOWPuDEPMA0GA1UECwwGQWxpcGF5MUMwQQYDVQQDDDrmlK/ku5jlrp0o5Lit5Zu9Kee9kee7nOaKgOacr+aciemZkOWFrOWPuC0yMDg4NjMxNTkzNzUyNDI1MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAqEX/n2nCk3qxQshl5Tf7HzRMhgYiSHJBdAECI9KK67hkqGF6VIbycdmopLuIsfCkloRfmxjXQ0Qr3vNuiMOWlhvDBntAlbI1TEvYqj3cdfE/yWxnIpi82VD3BtOxCZ82q3Gvhj3iRclPLp/PfJsoJ6qzBzeQkHXLJvB1OCA6mtgYCpYWEsRRy3OaMPsmigLBrTB3TfhDXpeP4qNhlM4Q8F3WTw5oeIShTa/qIJQDn0iRhzhndllUnv9qb5kZm/IUUYpQZKvyeh9A5sLxArpNe8v2G53I3JV8ugs7PhLAqjJyejQDhHuP5EfnIA3gJuPOTcAV9Y5lB0ux26Gk0kXTkwIDAQABoxIwEDAOBgNVHQ8BAf8EBAMCA/gwDQYJKoZIhvcNAQELBQADggEBABxeOnOq1RWe2/snIRMW4Aw1izWEjRHA8lXmZEq+4tE/JB+IMXn3JIOY79fe3Myx6tSuSf5uPPafKylq3o/uc3ohpoCnsl7aLqRHB6Mldpaw5d1Xc7Sw+HjjUGhwAgmPOvIAmnOYXFw+h2Dd41W9IVVQYe2/ntZJsbEciqw3+7UapVbvGECNPLTlv2rUJUlSx0FEwwH/P0YVpvL3RRX3yEWks7R2z07+CGVmO8LXmINpt6lJDfyjyTEl+kPrgCiZeGrQoy94xFiY/cd3+nYPM7mD8nLaoqqiyNivX5s3Eg0Cl3ygt8FaVYmDVMDnOfPhwd1mds+MD8f2GvRGluZGTEk=
  call-back-url: http://youxinruanjian.cn/alipay/callBack
  appCode: 9508b34b3f0249e7b483ed12013a0fe5
  pubPath: D:\workspace\youxinservers\src\main\resources\appCertPublicKey_2019103168821258.crt
  rootPath: D:\workspace\youxinservers\src\main\resources\alipayRootCert.crt
  pubJobPath: D:\workspace\youxinservers\src\main\resources\alipayCertPublicKey_RSA2.crt


  
  
  