server:
  port: 9898
spring:
  application:
    name: youxinservice
  mvc:
    favicon:
      enabled: false
  data:
    mongodb:
      uri: mongodb://120.76.101.139:28018/admin
      host: 127.0.0.1
      username: 
      password: 
      database: youxinapp
      port: 28018 
      connectTimeout: 20000
      socketTimeout: 20000
      maxWaitTime: 2000

  redis:
    host: 127.0.0.1
    port: 6379
    password: 
    database: 2
    isCluster: false
    timeout:
      seconds: 10000
    jedis:
      pool:
        max-active: 10000
        max-wait:
          seconds: 10000
        max-idle: 1000
        min-idle: 1000
        
       
authorizationfilter:
  requestUriList[0]: /user/register
  requestUriList[1]: /user/login
  requestUriList[2]: /other/randcode/sendSms
  requestUriList[3]: /user/updatePwdForSms
  requestUriList[4]: /config/get
  requestUriList[5]: /user/logout

youxin:
  apiKey: youxin 
  #是否检验接口 0不检验，1检验
  isAuth: 1 
  #是否保存请求日志 0否，1是
  isSaveRequestLogs: 0 
  #redis地址
  redisAddr: redis://127.0.0.1:6379
  #友讯号
  accountTitle: yx
  #是否开启定时任务
  openTask: 0
## 阿里云短信服务
smsconfig:
  product: Dysmsapi
  domain: dysmsapi.aliyuncs.com
  accesskeyid: LTAIPf3JXTTdhbVU
  accesskeysecret: acMpNNTELzuMKgJisolq9DztjTLmFE
  signname: 友信IM
  chinase-templetecode: SMS_164220086
  ## 图形验证码是否启用0不启用 1起用
  isstart: 0
  
###微信支付相关配置
wxconfig:
  appid: wx52ac911627154d31
  mchid: 1559973071
  secret: 31bbedb38c0707d6da871e353ff1f313
  api-key: youxunyouxunyouxunyouxunyouxunyx
  call-back-url: http://youxinapp.cn/user/recharge/wxPayCallBack
  pk-path: D:/Eclipse/WorkPace/mianshi-parent/mianshi-im-api/youxin.p12
  
#支付宝支付相关配置
alipayconfig:
  appid: 2019052165280837
  app-private-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC114nJdXFUPGaPxrGrJQaTItbhf8l6T2uiIq9L48b+r6gO/uSZ1mrJq3UYdJDprgXzIxXuf21BUof/e9Aib6+xTRkZdYf9WoYzKrFhHC3Xdo7sSHSzlezXjz+aWaglpnRp3oyKFUbzvXhzpR1d2xHB5luJJoXY3rHaUaDlg1CVFbI4Ix4VStn1lnfdoe4WNoP1r6V2PX7lCQCMLLycUgSviWotH+zB2irluHtQYu0Avvq5S5vObaan5Htat80TdxpsKBWoJy2W6ZQki0lmDXkeG6RNxhCOGO0qDppDnETrCIOQzyvyYHRz4cjR6b3eHyQU3xMPlubDDqaV3p/cDuUzAgMBAAECggEBALVIDkY3/eZDXN/i7sa238oZhm1CTuLPgHcf6vBWQNEw3vMsK0wuVUF92/uoYbuE0MumY7vjb1Ea7RfHICTkgRvZx7b407zA3V7vJeyxAgZ2XF+0kBtk0LvJRFglH5uBSTcuNZ+HPLfLYOSxbAhgWGCcvQ6KyA7/XAFRNXz5n4EvdDZbWoFicSMxir94qmCebkJ6jBw4GxfmqM2swTSaAs5+OOQLQOYBRXa/85nWUV0P5s6bJsXS+/SsCbFcgbDguaagCveVokWcIyA1wV3Jt0Ea8mx/F5wP5s9ELxxcp0H4aiLXQ0nYHiJAJpZJfE+3DFEGHxp9lTFubQ8Z9Osad/ECgYEA42YQ7tox68CVmXClsbNbONBWCf96k3bS5Be+RjAaL5gr0oGBZJ1SsSf9Ewo17sxImQ+r/l+9R+3UJktwRQ74/6zz08XoKYBAHcKOohyEGkEMxk+Pr7k3h32ZW57Z4JVtHph2v3qmMxPXs/60Fp8z9RlWf4upM1MJaY3Heb3KJTsCgYEAzLabDdUi7YjXA58tOwF9CUK12k1VLPOmILNuXngN6MRPWhsD2cBYpYESXTKwxnlTLyh2PpI7hTOdxsAlMwJdBD0uecB76AplbDmqHOdXMGvFuAf2hJXMW0ghen81JNAb58PIwYlpvC0WyvfIS8joKpUBo3DSAwN8ZxqYqcmW4GkCgYBo1fdchs+ZBrJxiRN6t1uI99OSzGuwbImRiri4FxkbdCZP6FDFGBq1feAY1Q5ER334wtbicTUMYkL6XLEnxV1aUlwe+BCugWgN0FJ9vnPQvsiq7KcrtlI5btgy+ysrdPhXsKaeZGcXCUDaxMQ14bPMfZ/5MWQSO2gNd8XNBIibXQKBgBr3Xvt2fRBfOzud5z5jls32fLASCctPGS4rlLlbBTIJUg6jimFPxh2fIAUo3UJ3zu5iXRkm+DI2t2zr+Lp8cDZTvOCK64eIfw2/ltoR21lkiPoSCnYyqWXI3ageQ6jixRpFnxdne4cvRVZdR4Q8JeEeGcYm4XNGLUgDp+KNzJMpAoGACoLotcGsUa69lHyYoJgIO1MzGlj2QpgQ5HG/CMMH68m5tFHUftXPa2WODvSc8teGhEm29PxSgIBSm6s545swRtMilDDFGwPs7+IwI738MqS5+kGSkJYR0kah8aYKaZtNbB0VK4yVg6Sy0mFEqOIyjUchjBdh23e7AAc+ZZw6Sh4=
  charset: utf-8
  alipay-public-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuEunTudnoTDAC0FA+vWBFdv6+EX1pMIuyBr+jFuuErptJMBfj5reyUcVAYfAcMQ2fkIFs5G7mfmxxRiC3VD4FfZLfeaD84tdMr+KUbf7ocqrA3Xrvw/+vHsNhWSU2/p8mq7ur3uj8nY74R7eOrkMDKX2UqY+J3mAgEAhvbSlsica81cKksqeOQHycfw6qLZJjW/geXqOdsVKdkuIVK76bjmLalf9L+7CqG0NBytuxhldb9ELH7/nngez3ituCfe56NC4phWNBcDVeSYZBVEZgPIJx9AvjVAVhHSGMS9zmith3EiIJD/GddCg/TTWc4KiqEGCqVRY3YYpA33P9igzzQIDAQAB
  call-back-url: http://youxinapp.cn/alipay/callBack
  appCode: 9508b34b3f0249e7b483ed12013a0fe5

  
  
  